cc_binary(
    name = "simple",
    srcs = ["simple/main.cpp"],
    deps = [
        "//src:clikit",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "iterative",
    srcs = ["iterative/main.cpp"],
    deps = [
        "//src:clikit",
    ],
    visibility = ["//visibility:public"],
)
