alias(
    name = "lib",
    actual = ":clikit",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clikit",
    srcs = ["clikit.hpp"],
    hdrs = [
        "clikit.hpp",
    ],
    deps = [
    ],
    visibility = ["//visibility:public"],
)
